### ISSUE TITLE
Failed to dump Unity 2018.4.5 System.ArgumentNullException (Parameter 'keyFunctionAddresses')

### ISSUE THREAD

**Issue by florcorgi** [SamboyCoding/Cpp2IL#241]
The game I'm trying to decompile is The Escapists on Android, using Unity 2018.4.5. During decompilation (I REALLY want to generate pseudocode and read through the game's code) Cpp2Il proceeds to bombard me with yellow errors for _every single method_:
Failed to dump method System.Void AIVisit::OnVisit(System.Int32) System.ArgumentNullException: Value cannot be null. (Parameter 'keyFunctionAddresses')
   at Cpp2IL.Core.Analysis.AsmAnalyzerBase`1..ctor(UInt64 methodPointer, IEnumerable`1 instructions, BaseKeyFunctionAddresses keyFunctionAddresses)
   at Cpp2IL.Core.Analysis.AsmAnalyzerBase`1..ctor(MethodDefinition definition, UInt64 methodPointer, IList`1 instructions, BaseKeyFunctionAddresses baseKeyFunctionAddresses)
   at Cpp2IL.Core.Cpp2IlApi.CreateAnalyzerForMethod(MethodDefinition methodDefinition, BaseKeyFunctionAddresses keyFunctionAddresses)

What could be the issue? I really want that source code. It refuses to dump it.

Here's the APK incase you wanna try it yourself: https://pixeldrain.com/u/9NsrAu5t
Arguments: `cpp2il.exe --just-give-me-dlls-asap-dammit --game-path=escapists.apk`
Cpp2IL Version: 2022.0.7

**Comment by SamboyCoding** [comment]
Does the game ship with only ArmV7 binaries (as opposed to, say, arm64/aarch64/etc)? That would be my first guess without being able to run or look at the code right now

**Comment by florcorgi** [comment]
yeah, looks like it, the only folder in the 'lib' folder is 'armeabi-v7a'. also 'assets/bin/Data' has a whole bunch of seemingly randomly named files, could that be obfuscation?
