### ISSUE TITLE
Metadata (and analysis?) Dumper doesn't filter out pipe (|) characters in filenames

### ISSUE THREAD

**Issue by Yaekith** [SamboyCoding/Cpp2IL#7]
When I was using the application on Kuboom (yet another il2cpp unity game), it crashed when processing Assembly-CSharp saying some shit about 
`Unhandled exception. System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'C:\Users\notmyname\Downloads\fuck\cpp2il_out\types\Assembly-CSharp\__LoadTexture_g___LoadTexture|4_0_d_metadata.txt'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at Cpp2IL.AssemblyBuilder.ProcessTypeContents(Il2CppMetadata metadata, PE cppAssembly, Il2CppTypeDefinition cppTypeDefinition, TypeDefinition ilTypeDefinition, Il2CppAssemblyDefinition imageDef)
   at Cpp2IL.AssemblyBuilder.ProcessAssemblyTypes(Il2CppMetadata metadata, PE theDll, Il2CppAssemblyDefinition imageDef)
   at Cpp2IL.Program.Main(String[] args)`

**Comment by SamboyCoding** [comment]
Ah, I forgot pipe wasn't a valid character in windows. Will fix.

**Comment by SamboyCoding** [comment]
Fixed in https://github.com/SamboyCoding/Cpp2IL/commit/1e0b07d6add633fc062d02d07c3fe3c27323c4a6
